### ISSUE TITLE
trim_trailing_whitespace not working

### ISSUE THREAD

**Issue by TuckerWhitehouse** [kidwm/brackets-editorconfig#2]
Did a clean install of Brackets 1.1 on OS X 10.10 with no other extensions installed, but the trim_trailing_whitespace = true seems to have no effect. I believe this option was working in the 1.0 release.

**Comment by coliff** [comment]
trim_trailing_whitespace = true is working correctly for me with Brackets 1.2 (running on OS X 10.10). I'd suggest re-trying now.

For reference my config file is:

# editorconfig.org

root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 2
indent_style = space
trim_trailing_whitespace = true

[*.js]
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false

**Comment by kidwm** [comment]
@TuckerWhitehouse It is working in my test case.
