### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by PhiLhoSoft** [kidwm/brackets-editorconfig#3]
I installed this extension via the Brackets Extension Manager, although I don't recall if it was by name or by the GitHub link (not sure if it makes a difference).

When I open the Developer Console, I see the message:

[NodeDomain] Error loading domain "editorconfig": Unable to load one of the modules: C:/Users/PhiLho/AppData/Roaming/Brackets/extensions/user/brackets-editorconfig/node/domain, reason: Cannot find module './lib/editorconfig'

Indeed, if I open this path, the node/lib directory is empty. On this repository, I see it as  lib @ 50e0dba, so I guess it involves some kind of symbolic link or equivalent.

I did a successful `npm install -g editorconfig`, but it makes no difference.
I tried a `git clone git@github.com:editorconfig/editorconfig-core-js.git` (and moved the files up one folder) but I ended with a complaint about a bluebird dependency... (which I saw when I did the npm command).

I suggest either a fix for Windows users, or at least some instructions to get it working (perhaps with the globally installed npm module).

**Comment by coliff** [comment]
I'm using this extension with WIndows 8.1 64-bit and latest version of Brackets (1.2) and it works fine. The node/lib directory is not empty. I'd suggest updating Brackets if you're not on the latest version and try installing the extension via the Extension Manager.

**Comment by kidwm** [comment]
@PhiLhoSoft Which Windows version did you use?
@coliff Thanks for your testimony :)

**Comment by PhiLhoSoft** [comment]
Windows 7 with Brackets 1.2. I will uninstall it and re-install it, to see if it makes a difference.
Thanks for the feedback.

**Comment by kidwm** [comment]
@PhiLhoSoft feel free to reopen this issue if you still failed on Windows
