### ISSUE TITLE
extension does not sanitize files

### ISSUE THREAD

**Issue by amitkeret** [kidwm/brackets-editorconfig#6]
Hi there,
I'm trying to use your extension without success.

Here's my `.editorconfig` file, which is placed at my project's root:

```
root = true

[*]
charset = utf-8
end_of_line = lf
indent_style = space
indent_size = 2
insert_final_newline = true
trim_trailing_whitespace = true
```

I know some of these are not yet supported, however nothing seems to work. For example - after placing a few trailing whitespacesat the end of lines and deleting the final new line and saving, the file does not "sanitize". After closing and re-opening the file, the whitespaces are still there and a newline final newline is still missing.

I should say that I am getting the file highlighted and it says "EditorConfig" for filetype, so the extension seems to trigger.

Is something missing?
Thanks

**Comment by kidwm** [comment]
Which OS do you use and brackets version?

**Comment by amitkeret** [comment]
Hi @kidwm 

I believe the bug was due to another module - brackets-phplinter. I have posted [an issue](https://github.com/phoenix3008/brackets-phplinter/issues/3).

Thanks!
