### ISSUE TITLE
support "laxcomma:true" for object literal 

### ISSUE THREAD

**Issue by shardool** [kidwm/brackets-editorconfig#7]
As brackets-beautify plugin honors rules specified in the .editorconfig file, I would like to specify laxcomma value and set it to true so that I can stop brackets-beautify plugin from placing the commas at the end of each item in the array and each property of an object literal. Currently, brackets-beautify plugin honors laxcomma for arrays only. However, object literals get corrected.
example :
var a = [
    'item1'
,'item2'
,'item3'
]
this is not bothered by the brackets-beautify plugin and all is well. However, when I type the following
var Person = {
firstName:'Douglas'
,lastName:'Crockford'
,homeTown:'Mississippi'
};

It gets corrected by the brackets-beautify plugin to
var Person = {
firstName:'Douglas',
lastName:'Crockford',
homeTown:'Mississippi'
};

**Comment by kidwm** [comment]
I think you should report this issue to brackets-beautify, editorconfig does not touch the specific part of language.

**Comment by shardool** [comment]
thanks man. Cheers :)
