### ISSUE TITLE
Indent space not working propperly

### ISSUE THREAD

**Issue by davidbarredo** [kidwm/brackets-editorconfig#8]
I have this .editorconfig:

```
root = true

[*]
indent_style = space
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.{js, html, json, md}]
indent_size = 4

[*.{css, scss, sass, less}]
indent_size = 2
```

And the plugin is taking 4 spaces for less files, if I change the css rule to:
`[*.less]
indent_size = 2`
it works

**Comment by kidwm** [comment]
I suggest you file this parsing issue to upstream:
https://github.com/editorconfig/editorconfig-core-js
