### ISSUE TITLE
Setting indent_size to zero is ignored

### ISSUE THREAD

**Issue by rajsite** [kidwm/brackets-editorconfig#9]
For html used in github-pages I keep the html indentation flat to keep rendered pages cleaner. This is mostly because [whitespace in liquid templating is a pain](https://github.com/Shopify/liquid/issues/216) and has been for years.

To assist with that I added the following in .editorconfig for use in brackets:

```
[*.html]
indent_style = space
indent_size = 0
```

However when I do this it looks like the indent_size is ignored for zero and instead an indent_size of two is used (probably because it's the default?). I tested indent_size with a value of one and two both of which work correctly.

**Comment by kidwm** [comment]
Yes, that would be ignored by Brackets.

**Comment by rajsite** [comment]
That appears to be so https://github.com/adobe/brackets/pull/10064

Thanks for the response!
